# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-26 05:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='users',
            new_name='user',
        ),
    ]
