# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-24 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='prodducts',
            new_name='products',
        ),
    ]
