# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-07 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180502_1740'),
        ('orders', '0004_auto_20180502_1457'),
    ]

    operations = [
    ]
